### ISSUE TITLE
After a teleport pressing escape opens the flyout

### ISSUE THREAD

**Issue by negue** [ScottIngram/UFO#10]
Since #9 doesn't work I use it without Auto-Close, when using the Druid Teleport, the flyout is closed but then when I just press Escape it opens that Flyout (sometimes all others as well, one by one) before passing the escape to actually open the Game Menu

That issue is pretty new, so definitely last 1-2 updates

**Comment by ScottIngram** [comment]
Thanks for the bug report!

I think this is the problem: 

Sometimes, the Blizzard UI will close all open windows, including any open UFOs (i.e. flyouts).   One such example of this is when casting Dreamwalk, a mage portal, or using a hearth stone and the UFO option "Auto-Close UFO" is disabled.  Another example is when a UFO is open and some event (such as walking though a portal, dungeon entrance, etc) triggers a screen reload.

When the above happens then the Escape key will mistakenly open those closed UFOs.

I'm working on a fix.  Thanks again!
