### ISSUE TITLE
Cannot Drag n Drop UFO to ElvUI Bar

### ISSUE THREAD

**Issue by obzen900** [ScottIngram/UFO#21]
I made a UFO button using 2 different macros. I named on ST and the AOE. I am using ELVUI 13.63 and UFO v10.2.6 on retail v10.2.6.54499. If I try to drag either of those UFO buttons I get this error:

107x UFO/ThirdPartyAddonSupport.lua:72: attempt to concatenate field 'btnNum' (a nil value)
[string "@UFO/ThirdPartyAddonSupport.lua"]:72: in function <UFO/ThirdPartyAddonSupport.lua:69>
[string "=(tail call)"]: ?
[string "@UFO/ui/ActionBarButtonMixin.lua"]:53: in function `getActionBarBtn'
[string "@UFO/Germ.lua"]:208: in function `new'
[string "@UFO/GermCommander.lua"]:108: in function `update'
[string "@UFO/GermCommander.lua"]:279: in function `handleActionBarSlotChanged'
[string "@UFO/UFO.lua"]:48: in function `?'
[string "@UFO/ScottFreeWowLibs/BlizGlobalEventsListener.lua"]:25: in function <...ns/UFO/ScottFreeWowLibs/BlizGlobalEventsListener.lua:24>
[string "=[C]"]: in function `PickupAction'
[string "@FrameXML/SecureHandlers.lua"]:140: in function <FrameXML/SecureHandlers.lua:133>
[string "@FrameXML/SecureHandlers.lua"]:402: in function <FrameXML/SecureHandlers.lua:382>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:408: in function <FrameXML/SecureHandlers.lua:382>
[string "=(tail call)"]: ?

Locals:
btnBarInfo = <table> {
 btnSlotIndex = 13
 actionBarDef = <table> {
 }
 barName = "Action"
 barNum = 2
 visibleIf = "bar:2"
 btnName = "ActionButton1"
}
btnSlotIndex = 13
barName = "ElvUI_Bar2"
(*temporary) = "ElvUI_Bar2"
(*temporary) = "Button"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'btnNum' (a nil value)"

**Comment by ScottIngram** [comment]
I fixed this bug, but be warned:  my support for ElvUI is half-assed at best.  UFO only works on some bars, and, their sizes are wonky.  Sorry :-(
