### ISSUE TITLE
[Feature request] Silent load

### ISSUE THREAD

**Issue by Sluimerstand** [ScottIngram/UFO#22]
Hello,

Awesome addon, only just discovered it. It suits my needs perfectly. Great job on this!

What I would love however, and I know this may be a bit niche, is an option to disable the chat message on logging in.

![image](https://github.com/user-attachments/assets/fe6a17fb-fd48-432d-8c46-15a65fe80e28)

It's a pet peeve of mine. :D

**Comment by ScottIngram** [comment]
fair enough.  I'll work it into the next release.

Meanwhile, you can turn it off yourself by using a text editor to change Ufo.lua and put a -- at the start of  line #99
https://github.com/ScottIngram/UFO/blob/master/UFO.lua#L99

**Comment by ScottIngram** [comment]
fixed and released to curseforge.
