### ISSUE TITLE
Bar name tooltip not disappearing until tooltip changes

### ISSUE THREAD

**Issue by Konsafloof** [ScottIngram/UFO#26]
When hovering over a bar its name will be stuck on your tooltip until the tooltip changes (Not really sure how to word it sorry, I did try with all addons disabled)
![2024-08-0415-36-42-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/a4517c9b-aa21-4d11-b013-b41ee4a3c337)

**Comment by ScottIngram** [comment]
Thanks for the helpful screen cap.  Yep, that's a bug.  I've set my config so that tooltips appear in one fixed location so this wasn't as noticeable for me as show here.  I'll look into this.  thanks!

**Comment by ScottIngram** [comment]
fixed and released to curseforge.  thanks again!
