### ISSUE TITLE
macro window has no UFO button

### ISSUE THREAD

**Issue by ScottIngram** [ScottIngram/UFO#28]
User [hayleqwyn](https://www.curseforge.com/members/hayleqwyn/projects) on curseforge reports:

> For some reason, there is no button for me to open UFO with the macro window. There doesn't seem to be any error being thrown however, so I don't know why. But it's making it very tedious to add macros to my flyouts, as I have to open the macro window, grab a macro, then open the spellbook or professions window (which closes the macro window) to add it to a flyout, making adding multiple macros take forever.

Yup, that's a pain, sorry.  I think it broke in the pre-patch and I missed it.  Should be easy to fix.

**Comment by ScottIngram** [comment]
I'm having trouble recreating this.  Are you using any addons that affect the macro window?

**Comment by Hayleqwyn** [comment]
Apparently, the addon Macro Toolkit was preventing the button from showing up. I tried disabling it, and the UFO button is now showing properly. Do you happen to know why that would be happening?

**Comment by ScottIngram** [comment]
Thanks for the extra info.  I found the problem
* the default Blizz macro window code loads on-demand when the user opens it. 
* my code was listening for that to happen and reacts by sticking the UFO button on it.
* MTK forces the Blizz macro window code to load "early"
* if MTK loads before UFO does, then UFO isn't there yet to hear the macro window code load.

I've written the bugfix.  UFO no longer assumes the macro window code is going to only load on-demand when the user opens it.  Now it will check to see if it's already loaded.

Also, UFO now detects MTK and gives it a UFO button too :-)

**Comment by ScottIngram** [comment]
fixed and released to curseforge.  thanks again!

**Comment by Hayleqwyn** [comment]
No problem! Thank you for figuring out the problem and how to fix it!
