### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by Katie-Fish** [ScottIngram/UFO#3]
it's probably me. 

i've set up a great fly-out with all my hearthstones and wormholes, it looks great, but has no functionality. the fly-out physics are great, but the buttons do not perform any function . no error message. 

i do run with addons, so i disabled all but UFO, and then added Ace3 because of errors. it seems to be error free at this point, just not functioning.

please help! what am i missing?

**Comment by ScottIngram** [comment]
Thanks for taking the time to report the error and sorry you're having trouble.  The Ace3 error is a big oops on my part, thanks for telling me.   I'll fix that and push it in the next release.

As for nothing happening, I'm sure that's another oops from me.   Let me ask a few questions:

Are you playing the game in English?  If not, a German user reported an bug that affects toys (such as hearth stones) for all non-English languages.  If you're using the original UFO release, please upgrade to the one I released 3 days ago which I hope solves the problem. Sadly, your flyout will still be broken but throwing it away and rebuilding it should work.  SORRY :-(   If that still doesn't work, then I haven't actually fixed the bug yet :-( so please let me know.

If you are playing in English, or, you are using the latest release... Hmmm... do any UFO buttons work?  Spells, pets, mounts, items, etc?

thanks!
-Scott

**Comment by ScottIngram** [comment]
A hearthstone / portal flyout was the first thing I did with UFO too :-)

BTW, I released a newer version to fix the Ace lib problem.

I wish there were a simple explanation but I'm not seeing it.

This may be a bit much to ask, but, can you go into your 
/Applications/World of Warcraft/_retail_/WTF/Account/YOUR-USER-NAME/SavedVariables

grab the "UFO.lua" file there and attach it to this thread, please?

thanks!

**Comment by ScottIngram** [comment]
Doh, silly github.  

Well, 1, ty.  I was able drop your config into my WoW.  And 2, crud, the buttons that could work (dreamwalk, cat form, etc... I was on my druid too) DID work, so that didn't shed any light on the problem.

You already said you've disable all other addons, so, that's not it.

Now I'm trying to think of some option in the Bliz menus that could affect the flyout buttons...

I'm really sorry it's not working for you.  I will think more and experiment to see if I can recreate this problem and find a fix.

**Comment by ScottIngram** [comment]
Wish I could say yes, but that's some noise I should really quiet.

**Comment by ScottIngram** [comment]
Hi Katie.  The latest release has a lot of new code that is a major rework of how buttons are defined and triggered.  There's a chance it may have fixed your problem.  I hope so.  Please feel free to give it a shot.

**Comment by ScottIngram** [comment]
Hi @Katie-Fish , we've fixed this problem with #9 
At least, I think that problem and this one are the same.  Please let me know if I'm wrong.
