### ISSUE TITLE
Not working on Dominos

### ISSUE THREAD

**Issue by StackExplode** [ScottIngram/UFO#7]
It seems not working on Dominos which is a popular action bar addon. I tried both 2 workarounds :
* Extra UI config:  in Dominos config dialog, I enabled "Show empty button" but when dragging UFO icon to action bar it sill show nothing.
* Placeholder: When dragging UFO icon to action bar a macro icon rather than the icon I set in UFO interface was created on the action bar but with no reaction when clicking it.

If you need further debug infomation please let me know how to get it. Thank you.

**Comment by ScottIngram** [comment]
Thanks for the useful details. I'll install Dominos and see what I can do to integrate with it.  No promises but I'll give it a shot.

**Comment by ScottIngram** [comment]
So far, I have been able to integrate UFO with Dominos.  However, when you point at empty buttons on some of the bars (but not all) the UI will throw a "Interface/FrameXML/SecureTemplates.lua:120: Wrong object type for function" and I haven't been able to figure out why.  Working on it.

**Comment by StackExplode** [comment]
> So far, I have been able to integrate UFO with Dominos. However, when you point at empty buttons on some of the bars (but not all) the UI will throw a "Interface/FrameXML/SecureTemplates.lua:120: Wrong object type for function" and I haven't been able to figure out why. Working on it.

Thank you for your update. I tried the latest version from curseforge, now UFO icon an be displayed on Dominos bar properly.  I got same error of "Wrong object type for function" and no reaction when clicking the sub icons in flyout menu. But when right click the parent icon, the first spell in it can be casted normally.

**Comment by ScottIngram** [comment]
> no reaction when clicking the sub icons in flyout menu

Others have mentioned this too.  If you have a moment to spare, can you tell me if this is still true when Dominos is disabled?  When all other addons are also disabled?

**Comment by StackExplode** [comment]
> > no reaction when clicking the sub icons in flyout menu
> 
> Others have mentioned this too. If you have a moment to spare, can you tell me if this is still true when Dominos is disabled? When all other addons are also disabled?

Hi, I got a fever this week and just recovered. I tried disabling Dominos and kept other addons, the error disappeared but still no reaction when clicking sub items in the flyout menu. Then I tried disabling all addons but kept UFO only. It turned out to be still no reaction with no error messages prompting. BTW, I'm using WoW client with Simplified Chinese language. I wonder if this caused the failure of the addon.

**Comment by ScottIngram** [comment]
thanks again for testing things for me.  I appreciate the work.

> still no reaction when clicking sub items in the flyout menu

You're not the only one reporting this problem (see #9 ).  I know the line of code causing the problem, but, I can't recreate it on my PC or my Mac.  So, I'm trying to think of a different way to achieve the same effect but with different code.  We developers lOvE when API calls fail silently and provide no info on why.  Yeehaw!

**Comment by ScottIngram** [comment]
Hey there @StackExplode  , the latest release fixes the problem with "still no reaction when clicking sub items."  You can grab it here or over on Curseforge.

I haven't made much more progress with Dominoes though.

**Comment by StackExplode** [comment]
I tested the latest release, it works fine with the latest version of Dominos(10.2.14b) in both 2 workaround modes. Thank you for your work. 🥂

**Comment by ScottIngram** [comment]
Awesome!  Thanks for reporting back :-)
